import datetime

DEBUG = False
BCRYPT_LOG_ROUNDS = 13
PROPAGATE_EXCEPTIONS = False
SQLALCHEMY_TRACK_MODIFICATIONS = False
JWT_TOKEN_LOCATION = 'cookies'
JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(days=1)
JWT_CSRF_CHECK_FORM = True
JWT_ACCESS_CSRF_FIELD_NAME = 'jwt_csrf_token'

PODCASTINDEX_API_KEY = 'ZBJFW42QYWT6C8PWB7EZ'
PODCASTINDEX_API_SECRET = 'dyHyKXSpJjn4J4rXYpj^DPsWNLjJ2j#VjJ38st9Q'

DEFAULT_USER_ID = 1

SQLALCHEMY_DATABASE_URI = 'sqlite:///../instance/musocial.db'

USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0"
